#!/usr/bin/env bash

executable="$1"
options="$2"
prime="prime-run"

if command -v $prime &> /dev/null
then
    echo "launching $executable $options with nvidia prime offloading"
    $prime $executable $options
else
    $executable $options
fi
